[package]
name = "fakesshd"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
russh = "0.49.1"
tokio = { version = "1.42.0", features = ["full"] }
